name: qwertyuiop Scan and Upload Results (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-test:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      
      - name: 执行Python脚本
        run: |
          python 1.py
        env:
          PYTHONUTF8: 1
      
      - name: 上传日志文件
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            test_output.txt
            error_details.txt
            fatal_error.log
